
public enum BUGSTATUS {
	NEW, ASSIGNED, OPEN, FIXED, PENDINGRETEST, RETEST, VERIFY, REOPEN, VERIFIED, CLOSED, REJECTED, DUPLICATE, DEFERRED,
	NOTABUG, NEEDMOREINFORMATION, WONTFIX, COULDNTREPRODUCE;

}
